
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: colbyfayock/applitools-eyes-action
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: Space Jelly Shop
        baseUrl: https://spacejelly.dev/
