name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: Space Jelly Shop
        baseUrl: https://spacejelly.dev
        concurrency: 20
        
  depth:
    runs-on: ubuntu-latest

    steps:
    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: Space Jelly Shop
        baseUrl: https://spacejelly.dev
        maxDepth: 2
        concurrency: 20

  sitemap:     
    runs-on: ubuntu-latest
    
    steps:
    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: 'Next.js WordPress Starter'
        sitemapUrl: https://next-wordpress-starter.netlify.app/sitemap.xml
        concurrency: 20

  large:
    runs-on: ubuntu-latest
    
    steps:
    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: 'Australia Post'
        baseUrl: https://auspost.com.au/shop/
        concurrency: 20
        maxDepth: 3
