name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: Space Jelly Shop
        baseUrl: https://spacejelly.dev

  test2:     
    runs-on: ubuntu-latest
    
    steps:
    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: 'Next.js WordPress Starter'
        sitemapUrl: https://next-wordpress-starter.netlify.app/sitemap.xml
